name: portfolio

services:
  server:
    container_name: portfolio_server
    image: portfolio/server:latest
    ports:
      - "7001:5000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
